#-------------CMT ENSIGHT POST PROCESSING SCRIPT
#------PURPOSE: Generates report template of Fluent Simulation for post processing
#------AUTHER: Arie Van Grootel
#------CREATED: ???
#------HOWTO: Insert description of how to use the cmd stuff
#------CHANGELOG: 
#------ 2021/02/26
#------ increased number of clip planes
#--------TO DO:
#------ 

ensight.part.select_default()
ensight.part.modify_begin()
ensight.part.elt_representation("3D_border_2D_full")
ensight.part.modify_end()
ensight.data.binary_files_are("native")
ensight.data.format("Fluent")
ensight.data.reader_option("'Load Internal Parts' OFF")
ensight.data.reader_option("'Use Meta Data Files' ON")
ensight.data.reader_option("'Load _M1 _M2 vars' OFF")
ensight.data.reader_option("'Load all cell types' OFF")
ensight.data.reader_option("'Poly to Regular Cell' ON")
ensight.data.reader_option("'Poly faced Hex to Poly' OFF")
ensight.data.reader_option("'Fix Hanging Nodes' ON")
ensight.data.reader_option("'Read Parallel CAS Variables' OFF")
ensight.data.reader_option("'Read Particle Variables' OFF")
ensight.data.reader_option("'Use Zone IDs for Parts' OFF")
ensight.data.reader_option("'Read all files to create variable list' OFF")
ensight.data.reader_option("'Console Output' 'Normal'")
ensight.data.reader_option("'Time Values' 'Read Time Values'")
ensight.data.result(r"""C:\\Users\\280592I\\Desktop\\AutoAero\\study\\SS-3002\\solved-22.22MS.cdat""")
ensight.data.shift_time(1.000000,0.000000,0.000000)
ensight.solution_time.monitor_for_new_steps("off")
ensight.data.replace(r"""C:\\Users\\280592I\\Desktop\\AutoAero\\study\\SS-3002\\solved-22.22MS.cas""")
ensight.part.select_begin(2)
ensight.part.visible("OFF")
ensight.part.select_begin(22)
ensight.part.visible("OFF")
ensight.part.select_begin(23)
ensight.part.visible("OFF")
ensight.part.select_begin(24)
ensight.part.visible("OFF")
ensight.part.select_begin(25)
ensight.part.visible("OFF")
ensight.part.select_begin(26)
ensight.part.visible("OFF")
ensight.part.select_begin(27)
ensight.part.visible("OFF")
ensight.variables.activate("VELOCITY")
ensight.variables.activate("Static_Pressure")
ensight.variables.activate("Vorticity_Magnitude")
ensight.viewport.select_begin(0)
ensight.view_transf.function("local")
ensight.view_transf.function("global")
ensight.view_transf.function("local")
ensight.view_transf.function("global")
ensight.view_transf.function("local")
ensight.frame.select_begin(0)
ensight.frame.modify_begin()
ensight.frame.symmetry_type("mirror")
ensight.frame.symmetry_mirror_x("ON")
ensight.frame.symmetry_use_file("OFF")
ensight.frame.modify_end()
ensight.view_transf.function("global")
ensight.view_transf.function("local")
ensight.view_transf.function("global")
ensight.views.use_stored_image("OFF")
ensight.views.rescale_views("ON")
ensight.views.load_dir("J:/SAE/CMT/2. Aero/Ensight/Ensight Home/Views")
ensight.part.select_begin(1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,28,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48)
ensight.part.colorby_palette("none")
ensight.part.colorby_rgb(0.6,0.6,0.6)
ensight.views.select(3)
ensight.views.apply()
ensight.views.select(3)
ensight.views.apply()
ensight.objs.core.STATES[0].add_state('New State',uuid='d52977bc-74de-11eb-8010-f334f21be67b',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].add_source('Image Source',uuid='ffa607bc-74de-11eb-a8a6-9f438a3a83ad',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['New State'][0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0].CHILDREN['Image Source'][0],0)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].add_source('Scene Geometry Source',uuid='01329ff0-74df-11eb-bf23-0f7f4199a1db',extension_name='scene_geometry_source')
ensight.objs.core.STATES[0].CHILDREN['New State'][0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0].CHILDREN['Scene Geometry Source'][0],0)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Geometry'
ensight.view_transf.function("global")
ensight.clip.select_default()
ensight.part.modify_begin()
ensight.clip.mesh_plane("Z")
ensight.part.modify_end()
ensight.part.modify_begin()
ensight.clip.value(1)
ensight.part.modify_end()
ensight.part.select_begin(2,29)
ensight.clip.begin()
ensight.clip.mesh_plane("Z")
ensight.clip.value(1)
ensight.clip.tool("xyz")
ensight.clip.slider_x(-5.00002193,5.00002193)
ensight.clip.slider_y(-2.94685542e-05,6.50002718)
ensight.clip.slider_z(-42.7968864,7.70315981)
ensight.clip.slider_step(2.52500224)
ensight.clip.end()
ensight.clip.create()
ensight.part.select_begin(55)
ensight.part.modify_begin()
ensight.part.colorby_palette("Vorticity_Magnitude")
ensight.part.modify_end()
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.visible("ON")
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.visible("ON")
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.visible("OFF")
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.width(0.030000)
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.height(0.750000)
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.text_position("right")
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.orientation("vertical")
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.location_x(0.050000)
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.location_y(0.125000)
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.visible("ON")
ensight.function.palette("Vorticity_Magnitude")
ensight.function.range(0,500)
ensight.function.number_of_levels(11)
ensight.legend.select_palette_begin("Vorticity_Magnitude")
ensight.legend.format("%g")
ensight.legend.width(0.0226322822)
ensight.legend.height(0.624876857)
ensight.legend.location_x(0.0292364378)
ensight.legend.location_y(0.283620685)
ensight.views.select(8)
ensight.views.apply()
ensight.views.select(8)
ensight.views.apply()
ensight.objs.core.STATES[0].add_state('New State',uuid='3206ce9e-74df-11eb-9429-17c1ef22f0d0',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],1)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Vorticity sweep'
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].add_source('Sweep Source',uuid='36e8ea78-74df-11eb-b325-3f2992ae9068',extension_name='sweep_source')
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].move(ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].CHILDREN['Sweep Source'][0],0)
ensight.objs.core.STATES[0].CREATE_REPORT_TEMPLATE=True
ensight.objs.core.STATES[0].USE_LOGO=True
ensight.objs.core.STATES[0].set_logo_file('J:/SAE/CMT/2. Aero/Ensight/Ensight Home/CMT Report logo.PNG')
ensight.objs.core.STATES[0].TEMPLATE_NAME='solved-16.67MS'
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].CHILDREN['Sweep Source'][0].SOURCE.set_params({'P0': 1.1, 'P1': -3.0, 'nc': 50, 'use_export_dialog': 0, 'width': 1493, 'height': 1015, 'AA': 1, 'var': ['Vorticity_Magnitude'], 'parts': ['Clip_plane'], 'rotate_count': 1, 'rotate_axis': 0, 'transient': 0})
ensight.part.select_begin(1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,28,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48)
ensight.part.select_begin(1)
ensight.part.visible("OFF")
ensight.part.select_begin(3)
ensight.part.visible("OFF")
ensight.part.select_begin(4)
ensight.part.visible("OFF")
ensight.part.select_begin(5)
ensight.part.visible("OFF")
ensight.part.select_begin(6)
ensight.part.visible("OFF")
ensight.part.select_begin(7)
ensight.part.visible("OFF")
ensight.part.select_begin(8)
ensight.part.visible("OFF")
ensight.part.select_begin(9)
ensight.part.visible("OFF")
ensight.part.select_begin(10)
ensight.part.visible("OFF")
ensight.part.select_begin(11)
ensight.part.visible("OFF")
ensight.part.select_begin(12)
ensight.part.visible("OFF")
ensight.part.select_begin(13)
ensight.part.visible("OFF")
ensight.part.select_begin(14)
ensight.part.visible("OFF")
ensight.part.select_begin(15)
ensight.part.visible("OFF")
ensight.part.select_begin(16)
ensight.part.visible("OFF")
ensight.part.select_begin(17)
ensight.part.visible("OFF")
ensight.part.select_begin(18)
ensight.part.visible("OFF")
ensight.part.select_begin(19)
ensight.part.visible("OFF")
ensight.part.select_begin(20)
ensight.part.visible("OFF")
ensight.part.select_begin(21)
ensight.part.visible("OFF")
ensight.part.select_begin(28)
ensight.part.visible("OFF")
ensight.part.select_begin(30)
ensight.part.visible("OFF")
ensight.part.select_begin(31)
ensight.part.visible("OFF")
ensight.part.select_begin(32)
ensight.part.visible("OFF")
ensight.part.select_begin(33)
ensight.part.visible("OFF")
ensight.part.select_begin(34)
ensight.part.visible("OFF")
ensight.part.select_begin(35)
ensight.part.visible("OFF")
ensight.part.select_begin(36)
ensight.part.visible("OFF")
ensight.part.select_begin(37)
ensight.part.visible("OFF")
ensight.part.select_begin(38)
ensight.part.visible("OFF")
ensight.part.select_begin(39)
ensight.part.visible("OFF")
ensight.part.select_begin(40)
ensight.part.visible("OFF")
ensight.part.select_begin(41)
ensight.part.visible("OFF")
ensight.part.select_begin(42)
ensight.part.visible("OFF")
ensight.part.select_begin(43)
ensight.part.visible("OFF")
ensight.part.select_begin(44)
ensight.part.visible("OFF")
ensight.part.select_begin(45)
ensight.part.visible("OFF")
ensight.part.select_begin(46)
ensight.part.visible("OFF")
ensight.part.select_begin(47)
ensight.part.visible("OFF")
ensight.part.select_begin(48)
ensight.part.visible("OFF")
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].capture()
ensight.part.select_begin(55)
ensight.part.modify_begin()
ensight.part.description("Vorticity Clip_plane")
ensight.part.modify_end()
ensight.part.visible("OFF")
ensight.clip.select_default()
ensight.part.modify_begin()
ensight.clip.mesh_plane("X")
ensight.part.modify_end()
ensight.part.modify_begin()
ensight.clip.value("MID-RANGE")
ensight.part.modify_end()
ensight.part.modify_begin()
ensight.clip.value(1)
ensight.part.modify_end()
ensight.part.select_begin(2,29)
ensight.clip.begin()
ensight.clip.mesh_plane("X")
ensight.clip.value(1)
ensight.clip.tool("xyz")
ensight.clip.slider_x(-5.00002193,5.00002193)
ensight.clip.slider_y(-2.94685542e-05,6.50002718)
ensight.clip.slider_z(-42.7968864,7.70315981)
ensight.clip.slider_step(0.500002205)
ensight.clip.end()
ensight.clip.create()
ensight.views.select(5)
ensight.views.apply()
ensight.views.select(5)
ensight.views.apply()
ensight.command.delay_refresh("ON")
ensight.view_transf.translate(-0.0330507495,-0.248797551,0)
ensight.part.select_begin(56)
ensight.part.modify_begin()
ensight.part.description("Side velocity Clip_plane")
ensight.part.modify_end()
ensight.part.select_begin(56)
ensight.part.modify_begin()
ensight.part.colorby_palette("VELOCITY")
ensight.part.modify_end()
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("ON")
ensight.function.palette("VELOCITY")
ensight.function.range(0,30)
ensight.function.number_of_levels(11)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.format("%g")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("OFF")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.width(0.030000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.height(0.750000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.text_position("left")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.orientation("horizontal")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.location_x(0.125000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.location_y(0.050000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("ON")
ensight.objs.core.STATES[0].add_state('New State',uuid='9adfa3d2-74df-11eb-9588-9b20a5ba642a',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],2)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Side velocity sweep'
ensight.objs.core.STATES[0].CHILDREN['Side velocity sweep'][0].add_source('Sweep Source',uuid='a0fbd326-74df-11eb-ba19-0fd9896ae690',extension_name='sweep_source')
ensight.objs.core.STATES[0].CHILDREN['Side velocity sweep'][0].move(ensight.objs.core.STATES[0].CHILDREN['Side velocity sweep'][0].CHILDREN['Sweep Source'][0],0)
ensight.objs.core.STATES[0].CREATE_REPORT_TEMPLATE=True
ensight.objs.core.STATES[0].USE_LOGO=True
ensight.objs.core.STATES[0].CHILDREN['Side velocity sweep'][0].CHILDREN['Sweep Source'][0].SOURCE.set_params({'P0': 1.0, 'P1': -1.0, 'nc': 2, 'use_export_dialog': 0, 'width': 1493, 'height': 1015, 'AA': 1, 'var': ['VELOCITY[]'], 'parts': ['Side velocity Clip_plane'], 'rotate_count': 1, 'rotate_axis': 0, 'transient': 0})
ensight.part.select_begin(56)
ensight.part.visible("OFF")
ensight.clip.select_default()
ensight.part.modify_begin()
ensight.clip.mesh_plane("Y")
ensight.part.modify_end()
ensight.part.modify_begin()
ensight.clip.value("MID-RANGE")
ensight.part.modify_end()
ensight.part.modify_begin()
ensight.clip.value(0)
ensight.part.modify_end()
ensight.part.select_begin(2,29)
ensight.clip.begin()
ensight.clip.mesh_plane("Y")
ensight.clip.value(0)
ensight.clip.tool("xyz")
ensight.clip.slider_x(-5.00002193,5.00002193)
ensight.clip.slider_y(-2.94685542e-05,6.50002718)
ensight.clip.slider_z(-42.7968864,7.70315981)
ensight.clip.slider_step(0.325002849)
ensight.clip.end()
ensight.clip.create()
ensight.part.select_begin(57)
ensight.part.modify_begin()
ensight.part.description("Vertical velocity Clip_plane")
ensight.part.modify_end()
ensight.part.select_begin(57)
ensight.part.modify_begin()
ensight.part.colorby_palette("VELOCITY")
ensight.part.modify_end()
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("ON")
ensight.views.select(6)
ensight.views.apply()
ensight.views.select(6)
ensight.views.apply()
ensight.view_transf.translate(0.0963941142,-0.0187269449,0)
ensight.view_transf.translate(-0.0163687784,0.00535054412,0)
ensight.objs.core.STATES[0].add_state('New State',uuid='dd154112-74df-11eb-8a9b-3ba264d532a8',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],3)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Vertical velocity sweep'
ensight.objs.core.STATES[0].CHILDREN['Vertical velocity sweep'][0].add_source('Sweep Source',uuid='e22e6fac-74df-11eb-935c-c7cec507baaf',extension_name='sweep_source')
ensight.objs.core.STATES[0].CHILDREN['Vertical velocity sweep'][0].move(ensight.objs.core.STATES[0].CHILDREN['Vertical velocity sweep'][0].CHILDREN['Sweep Source'][0],0)
ensight.objs.core.STATES[0].CREATE_REPORT_TEMPLATE=True
ensight.objs.core.STATES[0].USE_LOGO=True
ensight.objs.core.STATES[0].CHILDREN['Vertical velocity sweep'][0].CHILDREN['Sweep Source'][0].SOURCE.set_params({'P0': 0.0, 'P1': 1.3, 'nc': 2, 'use_export_dialog': 0, 'width': 1493, 'height': 1015, 'AA': 1, 'var': ['VELOCITY[]'], 'parts': ['Vertical velocity Clip_plane'], 'rotate_count': 1, 'rotate_axis': 0, 'transient': 0})
ensight.part.visible("OFF")
ensight.part.select_begin(1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,28,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48)
ensight.part.select_begin(1)
ensight.part.visible("ON")
ensight.part.select_begin(3)
ensight.part.visible("ON")
ensight.part.select_begin(4)
ensight.part.visible("ON")
ensight.part.select_begin(5)
ensight.part.visible("ON")
ensight.part.select_begin(6)
ensight.part.visible("ON")
ensight.part.select_begin(7)
ensight.part.visible("ON")
ensight.part.select_begin(8)
ensight.part.visible("ON")
ensight.part.select_begin(9)
ensight.part.visible("ON")
ensight.part.select_begin(10)
ensight.part.visible("ON")
ensight.part.select_begin(11)
ensight.part.visible("ON")
ensight.part.select_begin(12)
ensight.part.visible("ON")
ensight.part.select_begin(13)
ensight.part.visible("ON")
ensight.part.select_begin(14)
ensight.part.visible("ON")
ensight.part.select_begin(15)
ensight.part.visible("ON")
ensight.part.select_begin(16)
ensight.part.visible("ON")
ensight.part.select_begin(17)
ensight.part.visible("ON")
ensight.part.select_begin(18)
ensight.part.visible("ON")
ensight.part.select_begin(19)
ensight.part.visible("ON")
ensight.part.select_begin(20)
ensight.part.visible("ON")
ensight.part.select_begin(21)
ensight.part.visible("ON")
ensight.part.select_begin(28)
ensight.part.visible("ON")
ensight.part.select_begin(30)
ensight.part.visible("ON")
ensight.part.select_begin(31)
ensight.part.visible("ON")
ensight.part.select_begin(32)
ensight.part.visible("ON")
ensight.part.select_begin(33)
ensight.part.visible("ON")
ensight.part.select_begin(34)
ensight.part.visible("ON")
ensight.part.select_begin(35)
ensight.part.visible("ON")
ensight.part.select_begin(36)
ensight.part.visible("ON")
ensight.part.select_begin(37)
ensight.part.visible("ON")
ensight.part.select_begin(38)
ensight.part.visible("ON")
ensight.part.select_begin(39)
ensight.part.visible("ON")
ensight.part.select_begin(40)
ensight.part.visible("ON")
ensight.part.select_begin(41)
ensight.part.visible("ON")
ensight.part.select_begin(42)
ensight.part.visible("ON")
ensight.part.select_begin(43)
ensight.part.visible("ON")
ensight.part.select_begin(44)
ensight.part.visible("ON")
ensight.part.select_begin(45)
ensight.part.visible("ON")
ensight.part.select_begin(46)
ensight.part.visible("ON")
ensight.part.select_begin(47)
ensight.part.visible("ON")
ensight.part.select_begin(48)
ensight.part.visible("ON")
ensight.part.select_begin(1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,28,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48)
ensight.part.modify_begin()
ensight.part.colorby_palette("Static_Pressure")
ensight.part.modify_end()
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("ON")
ensight.function.palette("Static_Pressure")
ensight.function.range(-500,181.606)
ensight.function.range(-500,250)
ensight.function.number_of_levels(11)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("OFF")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.width(0.030000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.height(0.750000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.text_position("right")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.orientation("vertical")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.location_x(0.050000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.location_y(0.125000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("ON")
ensight.legend.width(0.0253114533)
ensight.legend.height(0.595320225)
ensight.legend.location_x(0.0225385129)
ensight.legend.location_y(0.318103433)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.format("%g")
ensight.views.select(2)
ensight.views.apply()
ensight.views.select(2)
ensight.views.apply()
ensight.objs.core.STATES[0].add_state('New State',uuid='1558b9f0-74e0-11eb-b987-1f9561a8e7e5',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],4)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='FW pressure'
ensight.objs.core.STATES[0].CHILDREN['FW pressure'][0].add_source('Image Source',uuid='1a4807a4-74e0-11eb-b070-e3761a50c4ad',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['FW pressure'][0].move(ensight.objs.core.STATES[0].CHILDREN['FW pressure'][0].CHILDREN['Image Source'][0],0)
ensight.views.select(1)
ensight.views.apply()
ensight.views.select(1)
ensight.views.apply()
ensight.objs.core.STATES[0].add_state('New State',uuid='21272276-74e0-11eb-a423-73e69ff2a056',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],5)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Frontal pressure'
ensight.objs.core.STATES[0].CHILDREN['Frontal pressure'][0].add_source('Image Source',uuid='25691470-74e0-11eb-a013-57cfbd095091',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['Frontal pressure'][0].move(ensight.objs.core.STATES[0].CHILDREN['Frontal pressure'][0].CHILDREN['Image Source'][0],0)
ensight.views.select(7)
ensight.views.apply()
ensight.views.select(7)
ensight.views.apply()
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("OFF")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.width(0.030000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.height(0.750000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.text_position("left")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.orientation("horizontal")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.location_x(0.125000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.location_y(0.050000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("ON")
ensight.objs.core.STATES[0].add_state('New State',uuid='2e73c42a-74e0-11eb-813a-8b8819984405',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],6)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Undertray pressure'
ensight.objs.core.STATES[0].CHILDREN['Undertray pressure'][0].add_source('Image Source',uuid='32911030-74e0-11eb-9caf-43e1e8c5a4ea',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['Undertray pressure'][0].move(ensight.objs.core.STATES[0].CHILDREN['Undertray pressure'][0].CHILDREN['Image Source'][0],0)
ensight.views.select(3)
ensight.views.apply()
ensight.views.select(3)
ensight.views.apply()
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("OFF")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.width(0.030000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.height(0.750000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.text_position("right")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.orientation("vertical")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.location_x(0.050000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.location_y(0.125000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("ON")
ensight.legend.width(0.0266510379)
ensight.legend.height(0.638669968)
ensight.legend.location_x(0.0265572686)
ensight.legend.location_y(0.27869457)
ensight.objs.core.STATES[0].add_state('New State',uuid='3d66952a-74e0-11eb-ad6b-43ed4e7f8ce8',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],7)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Iso pressure'
ensight.objs.core.STATES[0].CHILDREN['Iso pressure'][0].add_source('Image Source',uuid='4181866a-74e0-11eb-9c7a-a7eebac97673',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['Iso pressure'][0].move(ensight.objs.core.STATES[0].CHILDREN['Iso pressure'][0].CHILDREN['Image Source'][0],0)
ensight.views.select(6)
ensight.views.apply()
ensight.views.select(6)
ensight.views.apply()
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("OFF")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.width(0.030000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.height(0.750000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.text_position("left")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.orientation("horizontal")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.location_x(0.125000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.location_y(0.050000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("ON")
ensight.objs.core.STATES[0].add_state('New State',uuid='497bd4ba-74e0-11eb-8e0b-83f3c40a86c1',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],8)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Top pressure'
ensight.objs.core.STATES[0].CHILDREN['Top pressure'][0].add_source('Image Source',uuid='4cf33e12-74e0-11eb-bd72-03a0a239d0f9',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['Top pressure'][0].move(ensight.objs.core.STATES[0].CHILDREN['Top pressure'][0].CHILDREN['Image Source'][0],0)
ensight.part.select_begin(1,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,28,30,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48)
ensight.part.select_begin(1)
ensight.part.visible("OFF")
ensight.part.select_begin(3)
ensight.part.visible("OFF")
ensight.part.select_begin(5)
ensight.part.visible("OFF")
ensight.part.select_begin(6)
ensight.part.visible("OFF")
ensight.part.select_begin(7)
ensight.part.visible("OFF")
ensight.part.select_begin(8)
ensight.part.visible("OFF")
ensight.part.select_begin(9)
ensight.part.visible("OFF")
ensight.part.select_begin(10)
ensight.part.visible("OFF")
ensight.part.select_begin(11)
ensight.part.visible("OFF")
ensight.part.select_begin(12)
ensight.part.visible("OFF")
ensight.part.select_begin(13)
ensight.part.visible("OFF")
ensight.part.select_begin(14)
ensight.part.visible("OFF")
ensight.part.select_begin(15)
ensight.part.visible("OFF")
ensight.part.select_begin(16)
ensight.part.visible("OFF")
ensight.part.select_begin(17)
ensight.part.visible("OFF")
ensight.part.select_begin(18)
ensight.part.visible("OFF")
ensight.part.select_begin(19)
ensight.part.visible("OFF")
ensight.part.select_begin(20)
ensight.part.visible("OFF")
ensight.part.select_begin(21)
ensight.part.visible("OFF")
ensight.part.select_begin(28)
ensight.part.visible("OFF")
ensight.part.select_begin(30)
ensight.part.visible("OFF")
ensight.part.select_begin(32)
ensight.part.visible("OFF")
ensight.part.select_begin(33)
ensight.part.visible("OFF")
ensight.part.select_begin(34)
ensight.part.visible("OFF")
ensight.part.select_begin(35)
ensight.part.visible("OFF")
ensight.part.select_begin(36)
ensight.part.visible("OFF")
ensight.part.select_begin(37)
ensight.part.visible("OFF")
ensight.part.select_begin(38)
ensight.part.visible("OFF")
ensight.part.select_begin(39)
ensight.part.visible("OFF")
ensight.part.select_begin(40)
ensight.part.visible("OFF")
ensight.part.select_begin(41)
ensight.part.visible("OFF")
ensight.part.select_begin(42)
ensight.part.visible("OFF")
ensight.part.select_begin(43)
ensight.part.visible("OFF")
ensight.part.select_begin(44)
ensight.part.visible("OFF")
ensight.part.select_begin(45)
ensight.part.visible("OFF")
ensight.part.select_begin(46)
ensight.part.visible("OFF")
ensight.part.select_begin(47)
ensight.part.visible("OFF")
ensight.part.select_begin(48)
ensight.part.visible("OFF")
ensight.views.select(4)
ensight.views.apply()
ensight.views.select(4)
ensight.views.apply()
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("OFF")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.width(0.030000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.height(0.750000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.text_position("right")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.orientation("vertical")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.location_x(0.050000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.location_y(0.125000)
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("ON")
ensight.legend.width(0.0273208302)
ensight.legend.height(0.627832532)
ensight.legend.location_x(0.0332551897)
ensight.legend.location_y(0.28657636)
ensight.objs.core.STATES[0].add_state('New State',uuid='5d8403b0-74e0-11eb-845e-bfcaefd56657',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],9)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='RW pressure'
ensight.objs.core.STATES[0].CHILDREN['RW pressure'][0].add_source('Image Source',uuid='620ce582-74e0-11eb-8a48-6fddc733b59b',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['RW pressure'][0].move(ensight.objs.core.STATES[0].CHILDREN['RW pressure'][0].CHILDREN['Image Source'][0],0)
ensight.part.select_begin(1,28)
ensight.part.select_begin(1)
ensight.part.visible("ON")
ensight.part.select_begin(28)
ensight.part.visible("ON")
ensight.part.select_begin(3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48)
ensight.part.select_begin(3)
ensight.part.visible("ON")
ensight.part.select_begin(4)
ensight.part.visible("ON")
ensight.part.select_begin(5)
ensight.part.visible("ON")
ensight.part.select_begin(6)
ensight.part.visible("ON")
ensight.part.select_begin(7)
ensight.part.visible("ON")
ensight.part.select_begin(8)
ensight.part.visible("ON")
ensight.part.select_begin(9)
ensight.part.visible("ON")
ensight.part.select_begin(10)
ensight.part.visible("ON")
ensight.part.select_begin(11)
ensight.part.visible("ON")
ensight.part.select_begin(12)
ensight.part.visible("ON")
ensight.part.select_begin(13)
ensight.part.visible("ON")
ensight.part.select_begin(14)
ensight.part.visible("ON")
ensight.part.select_begin(15)
ensight.part.visible("ON")
ensight.part.select_begin(16)
ensight.part.visible("ON")
ensight.part.select_begin(17)
ensight.part.visible("ON")
ensight.part.select_begin(18)
ensight.part.visible("ON")
ensight.part.select_begin(19)
ensight.part.visible("ON")
ensight.part.select_begin(20)
ensight.part.visible("ON")
ensight.part.select_begin(21)
ensight.part.visible("ON")
ensight.part.select_begin(30)
ensight.part.visible("ON")
ensight.part.select_begin(31)
ensight.part.visible("ON")
ensight.part.select_begin(32)
ensight.part.visible("ON")
ensight.part.select_begin(33)
ensight.part.visible("ON")
ensight.part.select_begin(34)
ensight.part.visible("ON")
ensight.part.select_begin(35)
ensight.part.visible("ON")
ensight.part.select_begin(36)
ensight.part.visible("ON")
ensight.part.select_begin(37)
ensight.part.visible("ON")
ensight.part.select_begin(38)
ensight.part.visible("ON")
ensight.part.select_begin(39)
ensight.part.visible("ON")
ensight.part.select_begin(40)
ensight.part.visible("ON")
ensight.part.select_begin(41)
ensight.part.visible("ON")
ensight.part.select_begin(42)
ensight.part.visible("ON")
ensight.part.select_begin(43)
ensight.part.visible("ON")
ensight.part.select_begin(44)
ensight.part.visible("ON")
ensight.part.select_begin(45)
ensight.part.visible("ON")
ensight.part.select_begin(46)
ensight.part.visible("ON")
ensight.part.select_begin(47)
ensight.part.visible("ON")
ensight.part.select_begin(48)
ensight.part.visible("ON")
ensight.part.select_begin(1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,28,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48)
ensight.part.colorby_palette("none")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("OFF")
ensight.part.colorby_rgb(0.6,0.6,0.6)
ensight.views.select(6)
ensight.views.apply()
ensight.views.select(6)
ensight.views.apply()
ensight.view_transf.rotate(-39.1921272,0.964500904,0)
ensight.tools.plane("ON")
ensight.view_transf.rotate(-37.7733994,0.843935609,0)
ensight.view_transf.view_from_triad_axis("+x")
ensight.view_transf.rotate(2.66009951,1.92900181,0)
ensight.view_transf.function("plane")
ensight.view_transf.translate(-0.0512948036,-0.203301966,1.80364084)
ensight.view_transf.function("global")
ensight.view_transf.rotate(2.12807798,90.6630936,0)
ensight.view_transf.view_from_triad_axis("+z")
ensight.view_transf.rotate(1.5960592,2.89350271,0)
ensight.view_transf.function("plane")
ensight.view_transf.translate(0.0427417755,-0.0267688036,0.00290715694)
ensight.view_transf.function("global")
ensight.view_transf.rotate(-1.41872227,-0.723381042,0)
ensight.view_transf.function("plane")
ensight.view_transf.scale(0.542130053,-1.44177115,1)
ensight.view_transf.function("global")
ensight.view_transf.function("plane")
ensight.view_transf.translate(0.0106134415,-0.184778929,0.000974178314)
ensight.view_transf.function("global")
ensight.view_transf.rotate(9.75369263,-30.261219,0)
ensight.ptrace.select_default()
ensight.ptrace.default_emit_net(4,4)
ensight.part.select_begin(2,29)
ensight.ptrace.begin()
ensight.ptrace.variable("VELOCITY")
ensight.ptrace.end()
ensight.part.select_begin(2,29)
ensight.ptrace.begin()
ensight.ptrace.variable("VELOCITY")
ensight.ptrace.end()
ensight.ptrace.create_net(4,4)
ensight.part.select_begin(58)
ensight.part.modify_begin()
ensight.part.symmetry_type("mirror")
ensight.part.modify_end()
ensight.part.modify_begin()
ensight.part.symmetry_mirror_x("ON")
ensight.part.modify_end()
ensight.part.select_begin(58)
ensight.part.modify_begin()
ensight.part.colorby_palette("VELOCITY")
ensight.part.modify_end()
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("ON")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("ON")
ensight.view_transf.zoom(1.16031802)
ensight.view_transf.zoom(2.24246502)
ensight.part.delete()
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("OFF")
ensight.part.select_begin(2,29)
ensight.ptrace.begin()
ensight.ptrace.variable("VELOCITY")
ensight.ptrace.end()
ensight.ptrace.create_net(4,4)
ensight.part.select_begin(58)
ensight.part.modify_begin()
ensight.part.symmetry_type("mirror")
ensight.part.modify_end()
ensight.part.modify_begin()
ensight.part.symmetry_mirror_x("ON")
ensight.part.modify_end()
ensight.part.select_begin(58)
ensight.part.modify_begin()
ensight.part.colorby_palette("VELOCITY")
ensight.part.modify_end()
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("ON")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("ON")
ensight.part.select_begin(58)
ensight.ptrace.modify_netemit_points(0,20,4)
ensight.views.select(6)
ensight.views.apply()
ensight.views.select(6)
ensight.views.apply()
ensight.tools.plane("OFF")
ensight.objs.core.STATES[0].add_state('New State',uuid='392eb00e-74e1-11eb-8abc-fb09674affc5',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],10)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Top streamlines'
ensight.objs.core.STATES[0].CHILDREN['Top streamlines'][0].add_source('Image Source',uuid='3db62a94-74e1-11eb-9844-df39a2b81e85',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['Top streamlines'][0].move(ensight.objs.core.STATES[0].CHILDREN['Top streamlines'][0].CHILDREN['Image Source'][0],0)
ensight.views.select(3)
ensight.views.apply()
ensight.views.select(3)
ensight.views.apply()
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("OFF")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.width(0.030000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.height(0.750000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.text_position("right")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.orientation("vertical")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.location_x(0.050000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.location_y(0.125000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("ON")
ensight.legend.width(0.0266510379)
ensight.legend.height(0.59039408)
ensight.legend.location_x(0.0272270609)
ensight.legend.location_y(0.325985223)
ensight.legend.location_x(0.0232083071)
ensight.legend.location_y(0.330911338)
ensight.objs.core.STATES[0].add_state('New State',uuid='4c849d8a-74e1-11eb-92dc-9352b224f21d',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],10)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],11)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Iso streamlines'
ensight.objs.core.STATES[0].CHILDREN['Iso streamlines'][0].add_source('Image Source',uuid='52cd61d6-74e1-11eb-b70f-97563f67eb93',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['Iso streamlines'][0].move(ensight.objs.core.STATES[0].CHILDREN['Iso streamlines'][0].CHILDREN['Image Source'][0],0)
ensight.views.select(7)
ensight.views.apply()
ensight.views.select(7)
ensight.views.apply()
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("OFF")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.width(0.030000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.height(0.750000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.text_position("left")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.orientation("horizontal")
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.location_x(0.125000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.location_y(0.050000)
ensight.legend.select_palette_begin("VELOCITY")
ensight.legend.visible("ON")
ensight.objs.core.STATES[0].add_state('New State',uuid='5febc29a-74e1-11eb-a971-aba7c7383c23',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],12)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Undertray streamlines'
ensight.objs.core.STATES[0].CHILDREN['Undertray streamlines'][0].add_source('Image Source',uuid='657af848-74e1-11eb-b21c-5b41fc0c135b',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['Undertray streamlines'][0].move(ensight.objs.core.STATES[0].CHILDREN['Undertray streamlines'][0].CHILDREN['Image Source'][0],0)
ensight.views.select(6)
ensight.views.apply()
ensight.views.select(6)
ensight.views.apply()
ensight.part.select_begin(4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48)
ensight.part.modify_begin()
ensight.part.colorby_palette("Static_Pressure")
ensight.part.modify_end()
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("ON")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("ON")
ensight.part.select_begin(3,30)
ensight.part.modify_begin()
ensight.part.colorby_palette("Static_Pressure")
ensight.part.modify_end()
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("ON")
ensight.legend.select_palette_begin("Static_Pressure")
ensight.legend.visible("OFF")
ensight.view_transf.rotate(-28.1970406,1.20562077,0)
ensight.view_transf.rotate(0,0,-0.588798523)
ensight.objs.core.STATES[0].add_state('New State',uuid='858c5d5c-74e1-11eb-858b-db1c790b4d29',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],13)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Top streamlines with pressure'
ensight.objs.core.STATES[0].CHILDREN['Top streamlines with pressure'][0].add_source('Image Source',uuid='8c9b16ec-74e1-11eb-9a68-3bbf565453e1',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['Top streamlines with pressure'][0].move(ensight.objs.core.STATES[0].CHILDREN['Top streamlines with pressure'][0].CHILDREN['Image Source'][0],0)
ensight.view_transf.rotate(-59.054184,-0.602815747,0)
ensight.view_transf.rotate(3.19211841,-58.8345642,0)
ensight.view_transf.translate(-0.351020187,0.0695571527,0)
ensight.view_transf.rotate(1.77339888,-2.89350271,0)
ensight.view_transf.rotate(0,0,-2.00751805)
ensight.objs.core.STATES[0].add_state('New State',uuid='95e3ba60-74e1-11eb-8f73-d747a65f4c11',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],14)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Rear streamlines'
ensight.objs.core.STATES[0].CHILDREN['Rear streamlines'][0].add_source('Image Source',uuid='9ba3cb3e-74e1-11eb-bf02-a7ac0f538719',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['Rear streamlines'][0].move(ensight.objs.core.STATES[0].CHILDREN['Rear streamlines'][0].CHILDREN['Image Source'][0],0)
ensight.view_transf.rotate(0,0,-2.00751805)
ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].apply()
ensight.objs.core.STATES[0].CHILDREN['Top streamlines with pressure'][0].apply()
ensight.part.select_begin(58)
##########################################################################
ensight.core.nexus.ReportServer.create_local_database(r"""C:\\Users\\280592I\\Desktop\\AutoAero\\study\\SS-3002""")
ensight.core.nexus.ReportServer.launch_local_server(r"""C:\\Users\\280592I\\Desktop\\AutoAero\\study\\SS-3002""",port=None,connect=ensight.core.nexus.ReportServer.get_server(),terminate_on_python_exit=True)
ensight.core.nexus.ReportServer.get_server().set_username('nexus')
ensight.core.nexus.ReportServer.get_server().set_password('cei')
ensight.objs.core.STATES[0].update_tags('',new_session=False,random_session=False)
ensight.objs.core.STATES[0].generate_report()
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].apply()
ensight.part.select_begin(55)
ensight.part.visible("ON")
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].capture()
ensight.objs.core.STATES[0].CHILDREN['Side velocity sweep'][0].apply()
ensight.objs.core.STATES[0].CREATE_REPORT_TEMPLATE=True
ensight.objs.core.STATES[0].USE_LOGO=True
ensight.objs.core.STATES[0].CHILDREN['Side velocity sweep'][0].CHILDREN['Sweep Source'][0].SOURCE.set_params({'P0': 1.0, 'P1': -1.0, 'nc': 2, 'use_export_dialog': 0, 'width': 1493, 'height': 1015, 'AA': 1, 'var': ['VELOCITY[]'], 'parts': ['Side velocity Clip_plane'], 'rotate_count': 1, 'rotate_axis': 0, 'transient': 0})
ensight.objs.core.STATES[0].CHILDREN['Vertical velocity sweep'][0].apply()
ensight.objs.core.STATES[0].CREATE_REPORT_TEMPLATE=True
ensight.objs.core.STATES[0].USE_LOGO=True
ensight.objs.core.STATES[0].CHILDREN['Vertical velocity sweep'][0].CHILDREN['Sweep Source'][0].SOURCE.set_params({'P0': 0.0, 'P1': 1.3, 'nc': 2, 'use_export_dialog': 0, 'width': 1493, 'height': 1015, 'AA': 1, 'var': ['VELOCITY[]'], 'parts': ['Vertical velocity Clip_plane'], 'rotate_count': 1, 'rotate_axis': 0, 'transient': 0})
ensight.objs.core.STATES[0].update_tags('',new_session=False,random_session=False)
ensight.objs.core.STATES[0].generate_report()
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].apply()
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].CHILDREN['Sweep Source'][0].destroy()
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].add_source('Sweep Source',uuid='f3341e84-74e2-11eb-80d0-77546f564921',extension_name='sweep_source')
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].move(ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].CHILDREN['Sweep Source'][0],0)
ensight.objs.core.STATES[0].CREATE_REPORT_TEMPLATE=True
ensight.objs.core.STATES[0].USE_LOGO=True
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].CHILDREN['Sweep Source'][0].SOURCE.set_params({'P0': 1.0, 'P1': -3.0, 'nc': 2, 'use_export_dialog': 0, 'width': 1478, 'height': 1015, 'AA': 1, 'var': ['Vorticity_Magnitude'], 'parts': ['Vorticity Clip_plane'], 'rotate_count': 1, 'rotate_axis': 0, 'transient': 0})
ensight.objs.core.STATES[0].CREATE_REPORT_TEMPLATE=True
ensight.objs.core.STATES[0].USE_LOGO=True
ensight.objs.core.STATES[0].CHILDREN['Vorticity sweep'][0].CHILDREN['Sweep Source'][0].SOURCE.set_params({'P0': 1.0, 'P1': -3.0, 'nc': 40, 'use_export_dialog': 0, 'width': 1478, 'height': 1015, 'AA': 1, 'var': ['Vorticity_Magnitude'], 'parts': ['Vorticity Clip_plane'], 'rotate_count': 1, 'rotate_axis': 0, 'transient': 0})
ensight.objs.core.STATES[0].update_tags('',new_session=False,random_session=False)
ensight.objs.core.STATES[0].generate_report()
ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].apply()
ensight.views.select(3)
ensight.views.apply()
ensight.views.select(3)
ensight.views.apply()
ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].capture()
ensight.objs.core.STATES[0].CREATE_REPORT_TEMPLATE=True
ensight.objs.core.STATES[0].USE_LOGO=True
ensight.objs.core.STATES[0].CHILDREN['Side velocity sweep'][0].CHILDREN['Sweep Source'][0].SOURCE.set_params({'P0': 1.0, 'P1': -1.0, 'nc': 40, 'use_export_dialog': 0, 'width': 1493, 'height': 1015, 'AA': 1, 'var': ['VELOCITY[]'], 'parts': ['Side velocity Clip_plane'], 'rotate_count': 1, 'rotate_axis': 0, 'transient': 0})
ensight.objs.core.STATES[0].CREATE_REPORT_TEMPLATE=True
ensight.objs.core.STATES[0].USE_LOGO=True
ensight.objs.core.STATES[0].CHILDREN['Vertical velocity sweep'][0].CHILDREN['Sweep Source'][0].SOURCE.set_params({'P0': 0.0, 'P1': 1.3, 'nc': 30, 'use_export_dialog': 0, 'width': 1493, 'height': 1015, 'AA': 1, 'var': ['VELOCITY[]'], 'parts': ['Vertical velocity Clip_plane'], 'rotate_count': 1, 'rotate_axis': 0, 'transient': 0})
ensight.objs.core.STATES[0].update_tags('',new_session=False,random_session=False)
ensight.objs.core.STATES[0].generate_report()
ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].apply()
ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].destroy()
ensight.objs.core.STATES[0].add_state('New State',uuid='5291967a-74e5-11eb-9a66-eb6e0c926b30',capture=1)
ensight.objs.core.STATES[0].move(ensight.objs.core.STATES[0].CHILDREN['New State'][0],0)
ensight.objs.core.STATES[0].CHILDREN['New State'][0].DESCRIPTION='Geometry'
ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].add_source('Image Source',uuid='56acbf6e-74e5-11eb-88ad-f75230b041b0',extension_name='image_source')
ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].move(ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].CHILDREN['Image Source'][0],0)
ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].add_source('Scene Geometry Source',uuid='58b12a66-74e5-11eb-8c89-677372786772',extension_name='scene_geometry_source')
ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].move(ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].CHILDREN['Scene Geometry Source'][0],0)
ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].move(ensight.objs.core.STATES[0].CHILDREN['Geometry'][0].CHILDREN['Image Source'][0],0)
ensight.objs.core.STATES[0].update_tags('',new_session=False,random_session=False)
ensight.objs.core.STATES[0].generate_report()